- hosts: archlinux-home
  remote_user: ian
  become: true
  tasks:
  - name: Update 'pacman' cache
    pacman:
      update_cache: true
  - name: Update Arch Linux via 'pacman'
    pacman:
      upgrade: yes
